[profile.default]

out = "out"
libs = ["lib"]
src = "src"

version = "0.8.19"

#[profile.libraries]

#forge-std = { version = "latest" }
#chainlink-brownie-contracts = { version = "latest" }
#openzeppelin-contracts = { version = "latest" }

remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts',
    '@solmate=lib/solmate/src/',
   ]

   #'@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts'

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 500
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
